id: P004376
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG25557
  title: རྩི་ཤིང་གི་ཞིང་ཁམས།
  author: ''
  volumes:
    eb3691c3c9ec4638b94a63f3a6839a7a:
      image_group_id: I1KG25559
      title: ''
      volume_number: 1
      total_pages: 162
